export const defaultCategories = [
  "Software Engineering",
  "DevOps",
  "Design",
  "Marketing",
  "Product",
  "Data Science",
  "Quality Assurance",
  "Mobile Development",
  "Documentation",
  "Sales",
  "Customer Support",
  "Human Resources",
  "Finance",
  "Legal",
  "Operations",
  "Project Management",
  "Business Development",
  "Content Writing",
  "Graphic Design",
  "Video Editing",
  "Social Media",
  "SEO",
  "Cloud Computing",
  "Cybersecurity",
  "Database Administration",
  "Network Engineering",
  "System Administration",
  "Game Development",
  "AR/VR Development",
  "Blockchain Development",
  "Machine Learning",
  "AI Engineering",
  "Robotics",
  "Embedded Systems",
  "Hardware Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Architecture",
  "Healthcare",
  "Nursing",
  "Medical",
  "Pharmaceutical",
  "Biotechnology",
  "Research",
  "Education",
  "Teaching",
  "Training",
  "Consulting",
  "Accounting",
  "Auditing",
  "Investment Banking",
  "Real Estate",
  "Logistics",
  "Supply Chain",
  "Procurement",
  "Hospitality",
  "Travel",
  "Tourism",
  "Food & Beverage",
  "Retail",
  "E-commerce",
  "Fashion",
  "Beauty",
  "Fitness",
  "Sports",
  "Entertainment",
  "Media",
  "Journalism",
  "Publishing",
  "Translation",
  "Interpretation",
  "Legal Services",
  "Administrative",
  "Executive Assistant",
  "Office Management",
  "Receptionist",
  "Data Entry",
  "Virtual Assistant",
  "Customer Success",
  "Account Management",
  "Technical Support",
  "IT Support",
  "Help Desk",
  "Quality Assurance",
  "Testing",
  "Manual Testing",
  "Automation Testing",
  "Performance Testing",
  "Security Testing",
];

export const availableTags = [
  "Frontend",
  "Backend",
  "FullStack",
  "React",
  "NodeJS",
  "NextJS",
  "TypeScript",
  "JavaScript",
  "MongoDB",
  "AWS",
  "Docker",
  "Microservices",
  "API",
  "Python",
  "GraphQL",
  "Tailwind CSS",
  "Figma",
  "UI/UX",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "PHP",
  "Laravel",
  "Ruby",
  "Rails",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "Android",
  "iOS",
  "Vue.js",
  "Angular",
  "Svelte",
  "Redux",
  "Zustand",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "Elasticsearch",
  "Kafka",
  "RabbitMQ",
  "Kubernetes",
  "Terraform",
  "Jenkins",
  "GitHub Actions",
  "GitLab CI",
  "Azure",
  "GCP",
  "Firebase",
  "Supabase",
  "Prisma",
  "Sequelize",
  "Mongoose",
  "Webpack",
  "Vite",
  "Babel",
  "ESLint",
  "Prettier",
  "Jest",
  "Cypress",
  "Playwright",
  "Storybook",
];
